# Generated by Django 6.0.2 on 2026-02-08 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=20, verbose_name='WhatsApp номер')),
                ('product_list', models.TextField(verbose_name='Список товаров')),
                ('total_price', models.CharField(max_length=50, verbose_name='Сумма к оплате')),
                ('method', models.CharField(choices=[('credit', 'Кредит'), ('installment', 'Рассрочка')], max_length=20, verbose_name='Способ')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('declined', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
            options={
                'verbose_name': 'Заявка на кредит/рассрочку',
                'verbose_name_plural': 'Заявки на кредит/рассрочку',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Смартфоны', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(verbose_name='Ссылка на фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
