# Generated by Django 6.0.2 on 2026-02-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_orderrequest_remove_product_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderrequest',
            options={'verbose_name': 'Заявка на покупку', 'verbose_name_plural': 'Заявки на покупку'},
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='method',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('credit', 'Кредит / Рассрочка'), ('secret', 'Секретный код')], max_length=50, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp номер'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(default='Новый', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='total_price',
            field=models.CharField(max_length=50, verbose_name='Общая сумма'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Электроника', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='Цена (₸)'),
        ),
    ]
