# Generated by Django 6.0.2 on 2026-02-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_orderrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderrequest',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='term',
            field=models.IntegerField(default=0, verbose_name='Срок (мес.)'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='method',
            field=models.CharField(max_length=50, verbose_name='Способ'),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='WhatsApp номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='total_price',
            field=models.CharField(max_length=50, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='Смартфоны', max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(verbose_name='Ссылка на фото'),
        ),
    ]
