# Generated by Django 6.0.2 on 2026-02-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_orderrequest_options_orderrequest_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='method',
            field=models.CharField(max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
